#!/bin/sh
# export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# mount -o remount,rw /
mount -t devtmpfs devtmpfs /dev
mount -t proc none /proc
mount -t sysfs none /sys
cat <<EOF
 ██████╗ █████╗ ██████╗ ██╗      ██████╗ ███████╗
██╔════╝██╔══██╗██╔══██╗██║     ██╔═══██╗██╔════╝
██║     ███████║██████╔╝██║     ██║   ██║███████╗
██║     ██╔══██║██╔══██╗██║     ██║   ██║╚════██║
╚██████╗██║  ██║██║  ██║███████╗╚██████╔╝███████║
 ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝ ╚═════╝ ╚══════╝
EOF
. /etc/os-release && echo $PRETTY_NAME
echo $(uname -a)
/bin/sh
/carl-exit
