name: run task in upinevm

description: execute a script in the upinevm

inputs:
  script:
    description: "The script to run"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: ensure qemu is installed
      shell: sh
      run: |
        # TODO NOT LIKE THIS
        if ! which qemu-system-x86_64; then
          sudo apt-get update && sudo apt-get install -y qemu-system-x86
        fi
        # if ! which musl-gcc; then
        #   sudo apt-get update && sudo apt-get install -y musl-tools libelf-dev
        # fi

    - name: run script
      shell: sh
      run: |
        ${{ inputs.script }}
