name: cache-test

on:
  workflow_call:

jobs:
  check_directory:
    runs-on: ubuntu-latest

    outputs:
      dir_exists: ${{ steps.check.outputs.dir_exists }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
