name: carlvm-build

on:
  push:
    branches:
      - main
    paths:
      - "carlvm/**"

env:
  SRCDIR: carlvm/src
  BUILDDIR: build/carlvm
  CACHEDIR: build/cache
  KERNELVER: 6.6.58
  ALPINEVER: 3.20.3

jobs:
  build-carlvm:
    uses: ./.github/workflows/build_carlvm.yml
