name: carlvm-build

on:
  push:
    branches:
      - main

env:
  SRCDIR: carlvm/src
  BUILDDIR: build/carlvm
  CACHEDIR: build/cache
  KERNELVER: 6.6.58
  ALPINEVER: 3.20.3

jobs:
  build-carlvm:
    runs-on: ubuntu-latest
    steps:
      - name: build carlvm
        uses: thetanil/userdoc/.github/workdflows/actions/build_carlvm@main
