name: make-image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils
