name: Build and Release

on:
  push:
    # tags:
    #   - "v*"

jobs:
  build_dumb_init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make

      - name: Build dumb-init
        run: |
          echo "Building dumb init"
          gcc -O2 abuild/qemu-kernel-build/src/dumb-init/dumb-init.c -o abuild/qemu-kernel-build/src/dumb-init/dumb-init

      - name: Upload kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: dumb-init
          path: abuild/qemu-kernel-build/src/dumb-init/dumb-init

  build_kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gcc make build-essential

      - name: Download kernel source
        run: |
          echo "Downloading kernel source"
          curl -O https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.6.58.tar.xz
          tar xvf linux-6.6.58.tar.xz -C /tmp/
          cp abuild/qemu-kernel-build/src/qemu-kernel-config /tmp/linux-6.6.58/.config

      - name: Build kernel
        run: |
          echo "Building kernel"
          cd /tmp/linux-6.6.58
          ls -la
          make -j8
          ls -la arch/x86/boot/bzImage

      - name: Upload kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: bzImage
          path: /tmp/linux-6.6.58/arch/x86/boot/bzImage

  build_alpine_rootfs:
    runs-on: ubuntu-latest
    needs: [build_dumb_init]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download alpine rootfs
        run: |
          echo "Downloading alpine rootfs"
          curl -O https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/x86_64/alpine-minirootfs-3.20.3-x86_64.tar.gz
          mkdir -pv /tmp/alpine-rootfs
          tar xvf alpine-minirootfs-3.20.3-x86_64.tar.gz -C /tmp/alpine-rootfs

      - name: download dumb-init
        uses: actions/download-artifact@v4
        with:
          name: dumb-init
          path: /tmp/alpine-rootfs

      - name: Prepare rootfs
        run: |
          # chmod +x /tmp/alpine-rootfs/init
          chmod +x /tmp/alpine-rootfs/dumb-init
          cd /tmp/alpine-rootfs
          find . | cpio -o -H newc > /tmp/alpine-rootfs.cpio

      - name: Upload alpine rootfs artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine-rootfs.cpio
          path: /tmp/alpine-rootfs.cpio

  release:
    runs-on: ubuntu-latest
    needs: [build_kernel, build_alpine_rootfs]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download kernel artifact
        uses: actions/download-artifact@v4
        with:
          name: bzImage
          path: output/bzImage

      - name: Download alpine rootfs artifact
        uses: actions/download-artifact@v4
        with:
          name: alpine-rootfs.cpio
          path: output/alpine-rootfs.cpio

      - name: Bundle output into zip
        run: zip -r output.zip output

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: output.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
