name: Release Carl

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name"
        required: true
      release_name:
        description: "Release name"
        required: true

permissions:
  contents: write

jobs:
  build-carlvm:
    uses: ./.github/workflows/build_carlvm.yml

  create_release:
    runs-on: ubuntu-latest
    needs: build-carlvm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download carlvm artifact
        uses: actions/download-artifact@v4
        with:
          name: carlvm
          path: ./build/carlvm-${{ github.event.inputs.tag_name }}

      - name: Create Tag
        run: |
          git tag ${{ github.event.inputs.tag_name }}
          git push origin ${{ github.event.inputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          draft: false
          prerelease: false

      - name: ls carlvm zip
        run: |
          ls -la build/carlvm-${{ github.event.inputs.tag_name }}
          zip -r build/carlvm-${{ github.event.inputs.tag_name }}.zip build/carlvm-${{ github.event.inputs.tag_name }}
          cat build/carlvm-${{ github.event.inputs.tag_name }}/qrun.sh build/carlvm-${{ github.event.inputs.tag_name }}.zip > build/carlvm-${{ github.event.inputs.tag_name }}.vm
          chmod +x build/carlvm-${{ github.event.inputs.tag_name }}.vm

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/carlvm-${{ github.event.inputs.tag_name }}.vm
          asset_name: carlvm-${{ github.event.inputs.tag_name }}.vm
          asset_content_type: application/octet-stream
