name: upinevm build firstboot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CACHEPATH: /tmp/upinevm-cache
      # override in .env
      UPINEVM_OUTPUTPATH: /tmp/upinevm-output

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: musl-gcc compile and strip
        run: |
          # TODO NOT LIKE THIS
          if ! which musl-gcc; then
            sudo apt-get update && sudo apt-get install -y musl-tools libelf-dev
          fi
          if ! which nasm; then
            sudo apt-get update && sudo apt-get install -y nasm
          fi

      - name: run bootstrap
        run: |
          mkdir -pv $UPINEVM_CACHEPATH
          mkdir -pv $UPINEVM_OUTPUTPATH
          if [ ! -f $UPINEVM_OUTPUTPATH/bzImage ]; then
            cd upinevm && UPINEVM_NOLAUNCH=1 ./bootstrap.sh
          fi
          echo UPINEVM_OUTPUTPATH=$UPINEVM_OUTPUTPATH
          ls -la $UPINEVM_OUTPUTPATH
          echo UPINEVM_CACHEPATH=$UPINEVM_CACHEPATH
          ls -la $UPINEVM_CACHEPATH

      # - name: run qrun
      #   run: |
      #     ./qrun.sh
