name: Build upinevm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-upinevm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: diatribes/upinevm

      - name: musl-gcc compile and strip
        run: |
          # TODO NOT LIKE THIS
          if ! which musl-gcc; then
            sudo apt-get update && sudo apt-get install -y musl-tools libelf-dev
          fi
          if ! which nasm; then
            sudo apt-get update && sudo apt-get install -y nasm
          fi

      - name: run bootstrap
        run: |
          ./bootstrap.sh

      - name: run qrun
        run: |
          ./qrun.sh
